import type { ContentBundle } from "./content-types";
import { ARTICLE_META } from "./insights-index";

export const en: ContentBundle = {
  SITE: {
    name: "CETL Institute",
    fullName: "Central European Tech Leadership Institute",
    url: "https://cetl-institute.vercel.app",
    email: "office@cetl-institute.eu",
    formEmail: "vorstand@eqaf.eu",
    location: "Vienna, Austria",
    region: "Central Europe",
    academic: "TU Wien, Academic Director",
    tagline: "Bridging the gap between academic excellence, industry practice and real execution.",
    complianceNote:
      "All CETL activities are directed exclusively at organizations outside the insurance sector. Insurance-specific compliance, regulatory topics and business mandates are explicitly excluded.",
  },

  NAV_LINKS: [
    { label: "ELaaS", href: "#elaas" },
    { label: "Portfolio", href: "#portfolio" },
    { label: "Packages", href: "#packages" },
    { label: "Programmes", href: "#programmes" },
    { label: "Ecosystem", href: "#ecosystem" },
    { label: "Evidence", href: "#evidence" },
    { label: "Institute", href: "#about" },
    { label: "Insights", href: "/insights" },
  ],

  MANAGING_DIRECTOR: {
    name: "Alin Kalam",
    initials: "AK",
    title: "Managing Director",
    headline: "Head of AI Coordination & Market Intelligence, UNIQA Insurance Group",
    location: "Vienna, Austria",
    linkedin: "https://www.linkedin.com/in/alinkalam/",
    bio: "20+ years at the intersection of AI strategy, data governance and enterprise execution: AI coordination and market intelligence at UNIQA International, BI leadership at Lufthansa Group, and Big Data at BAWAG P.S.K. Trained in engineering, business, and astrophysics at TU Wien, CEU, and the University of Vienna.",
    credentials: [
      { label: "UNIQA Insurance Group", sub: "Head of AI Coordination & Market Intelligence", logo: "/logos/uniqa.svg" },
      { label: "Lufthansa Group", sub: "Strategic BI & Analytics Lead", logo: "/logos/lufthansa.svg" },
      { label: "BAWAG P.S.K.", sub: "Big Data Officer", logo: "/logos/bawag.svg" },
      { label: "TU Wien", sub: "MSc, Engineering Management", logo: "/logos/tuwien.svg" },
    ],
    focus: ["AI Strategy & Governance", "Decision Intelligence", "Market Intelligence", "Data Strategy"],
  },

  PORTFOLIO_PRODUCTS: [
    {
      number: "1",
      title: "Executional Learning as a Service",
      accentLine: "Our core USP",
      description: "A standardized Data & AI foundation combined with organization-specific activation, use-case enablement and role-based learning journeys.",
      capabilities: [
        "Standardized 8-day Data & AI Foundation Programme",
        "Tailored to the organization's industry, roles, strategy and use-case reality",
        "Separate 7-day Executional Track Pool for cohort-specific enablement",
        "Use-case assessment and prioritization",
        "Strategic-fit and cross-business alignment",
        "Mentoring and one-to-one enablement",
        "Academic backbone through CETL's university and professional ecosystem",
      ],
      outcomeLabel: "Standardized core + customized activation",
      cta: "Explore ELaaS",
      ctaHref: "#elaas",
    },
    {
      number: "2",
      title: "Customized Education Design & Delivery",
      accentLine: "Designed for your context",
      description: "Individually designed Data, AI and innovation learning programmes for specific business contexts, maturity levels, organizational roles and target groups.",
      capabilities: [
        "Individually designed learning programmes on request",
        "Tailored education design for specific business contexts",
        "Modular journeys for leaders, business experts and technical staff",
        "Cross-functional learning formats",
        "Academic and professional delivery ecosystem",
        "Certification pathways where formally available",
        "Internal adoption and organizational relevance",
      ],
      outcomeLabel: "From targeted training to full learning journeys",
      cta: "Design a Customized Programme",
      ctaHref: "mailto:vorstand@eqaf.eu",
    },
    {
      number: "3",
      title: "Embedded Engineering & Capability Activation",
      accentLine: "Enablement close to the work",
      description: "CETL experts work alongside organizational teams to activate use cases, validate solutions, enable workflows and transfer technical capability directly into the organization.",
      capabilities: [
        "Use-Case Activation",
        "Prototyping & Validation",
        "Workflows & Automation",
        "No-Code / Low-Code Enablement",
        "Technical Enablement",
        "Knowledge Transfer",
        "Forward-Deployed-Engineer-inspired delivery",
        "Support aligned with team maturity and real problem context",
      ],
      outcomeLabel: "Capability transfer through joint execution",
      cta: "Explore Embedded Engineering",
      ctaHref: "#embedded",
    },
    {
      number: "4",
      title: "Community, Exchange, Enablement & Co-Create",
      accentLine: "Community-powered execution",
      description: "CETL activates its wider community and partner ecosystem to frame challenges, exchange knowledge, co-create solution pathways and generate early execution momentum.",
      capabilities: [
        "Technology exchange and expert impulses",
        "Cross-industry input and hackathons",
        "Expert network and partners",
        "Real business and technical challenges",
        "Solution concepts and prototypes",
        "University and industry collaboration",
        "Execution pathways",
      ],
      outcomeLabel: "From community knowledge to real projects",
      cta: "Bring a Challenge to CETL",
      ctaHref: "mailto:vorstand@eqaf.eu",
    },
  ],

  PACKAGES: [
    {
      number: "1",
      name: "Executional Learning Foundation",
      subtitle: "Customized Data & AI foundation + executional enablement",
      description: "A structured foundation programme tailored to the organization's industry, roles, processes and strategic priorities.",
      includes: [
        "8-day customized Data & AI Foundation Programme",
        "Industry- and organization-tailored customization",
        "Alignment with roles, processes and strategy",
        "Needs assessment and educational discovery",
        "7-day Executional Learning support pool",
        "Mentoring, use-case ideation and online sessions",
        "Panels, community impulses and cohort enablement",
        "Academic and industry-led delivery through CETL's ecosystem",
      ],
      price: "€35,000",
      priceNote: "For up to 20 participants",
      cta: "Discuss the Foundation Package",
      ctaHref: "mailto:vorstand@eqaf.eu",
    },
    {
      number: "2",
      label: "MOST POPULAR",
      name: "Executional Learning Customized",
      subtitle: "Foundation + role-based specialization + deeper executional support",
      description: "CETL's broader organizational package for combining a common foundation with concrete role-specific learning journeys and deeper execution support.",
      includes: [
        "Everything in Package 1",
        "9 additional specialization training days",
        "Up to 3 organizational roles or tracks",
        "Potential tracks: Everyday AI, Business AI, AI Expert and AI Leadership",
        "6 additional Executional Learning support days",
        "Use-case refinement, mentoring and guided project support",
        "Online enablement and implementation-oriented activation",
      ],
      price: "€65,000",
      priceNote: "For up to 20 participants",
      cta: "Design a Customized Package",
      ctaHref: "mailto:vorstand@eqaf.eu",
      featured: true,
    },
    {
      number: "3",
      label: "FLAGSHIP",
      name: "Flagship Embedded Engineering",
      subtitle: "All in Customized, plus embedded engineering and operational activation",
      description: "For organizations that want to move from enablement to execution with embedded technical capability and strong knowledge transfer.",
      includes: [
        "Everything in Packages 1 and 2",
        "Embedded Engineering — Forward-Deployed-Engineer-inspired approach",
        "AI/ML engineers or data scientists embedded with internal teams",
        "Co-creation around prioritized use cases",
        "Prototyping, validation and implementation pathways",
        "Workflow and operational integration",
        "Capability transfer and internal activation",
        "Scope tailored to duration, team composition and ambition",
      ],
      price: "Tailored to scope and duration",
      cta: "Scope an Embedded Engagement",
      ctaHref: "mailto:vorstand@eqaf.eu",
      featured: true,
    },
    {
      number: "4",
      label: "COMMUNITY",
      name: "Executional Community Package",
      subtitle: "Community-powered co-creation for real technical and AI challenges",
      description: "Activate CETL's wider ecosystem to frame, challenge and solve a focused business or technical problem through hackathon and community power.",
      includes: [
        "Organizational AI or technology challenge into CETL Tech Hackathon context",
        "Access to CETL academic, industry, community and developer ecosystem",
        "Challenge framing, data preparation and model-readiness support",
        "Community co-creation, proof-of-concept ideas and solution pathways",
        "Three months of structured post-format support",
        "Refinement, validation and next-step definition",
        "Early execution momentum",
      ],
      price: "€5,000–€12,000",
      priceNote: "Depending on challenge scope",
      cta: "Bring Your Challenge",
      ctaHref: "mailto:vorstand@eqaf.eu",
    },
  ],

  PRODUCT_GROUPS: [
    {
      label: "Our Products: Executional Learning",
      cards: [
        {
          number: "1",
          titleLine1: "EXECUTIONAL LEARNING",
          titleLine2: "FOUNDATION",
          tagline: "Customized AI & data foundation with practical enablement",
          description: "A structured entry offering that aligns core capability building with business context and real-world application.",
          includes: [
            { icon: "GraduationCap", text: "Foundational AI & data learning" },
            { icon: "Users", text: "Role- and context-aware customization" },
            { icon: "Target", text: "Strategic orientation and use-case framing" },
            { icon: "BookOpen", text: "Access to academic and expert-supported delivery" },
          ],
          footer: [{ icon: "ShieldCheck", text: "Core foundation for business activation" }],
        },
        {
          number: "2",
          ribbon: "MOST POPULAR",
          featured: true,
          titleLine1: "EXECUTIONAL LEARNING",
          titleLine2: "CUSTOMIZED",
          tagline: "Foundation plus role-based deepening and practical application",
          description: "A flexible package for organizations that want to translate learning into function-specific capability development.",
          includes: [
            { icon: "CheckCircle2", text: "Everything from the foundation layer" },
            { icon: "User", text: "Role-based specialization pathways" },
            { icon: "Star", text: "Extended executive and expert learning formats" },
            { icon: "BarChart2", text: "Project-oriented enablement and mentoring" },
          ],
          footer: [
            { icon: "Layers", text: "Foundation Layer" },
            { icon: "Share2", text: "Specialization Layer" },
          ],
        },
        {
          number: "3",
          ribbon: "FLAGSHIP",
          titleLine1: "FLAGSHIP",
          titleLine2: "EMBEDDED ENGINEERING",
          tagline: "Embedded activation for execution, adoption and measurable progress",
          description: "For organizations ready to move beyond learning into hands-on implementation with embedded support.",
          includes: [
            { icon: "Layers", text: "Everything from Packages 1 + 2" },
            { icon: "Settings2", text: "Embedded engineering and implementation support" },
            { icon: "Share2", text: "Prototyping, workflow integration and activation" },
            { icon: "Users", text: "Strong knowledge transfer into internal teams" },
          ],
          footer: [{ icon: "Target", text: "Execution support close to the work" }],
        },
        {
          number: "4",
          ribbon: "COMMUNITY",
          titleLine1: "EXECUTIONAL",
          titleLine2: "COMMUNITY PACKAGE",
          tagline: "Community-powered co-creation for AI, data and innovation challenges",
          description: "Activates the broader ecosystem to challenge, refine and accelerate ideas through collaborative formats.",
          includes: [
            { icon: "Handshake", text: "Participation at our flagship hackathon with partners such as City of Vienna, Vienna Business Agency, ÖBB, Sustainista and other ecosystem partners" },
            { icon: "UsersRound", text: "Dedicated workshops and community-centric solution sessions before and after the hackathon for your individual challenges" },
            { icon: "Lightbulb", text: "Access to one of the largest data & AI communities in the DACH region, connecting 15+ universities and academic bodies" },
            { icon: "Rocket", text: "Ideal for collaboration, challenge framing, validation and early momentum" },
          ],
          footer: [{ icon: "UsersRound", text: "Community-powered collaboration for real innovation momentum" }],
        },
      ],
    },
    {
      label: "Our Products: Executional Assessments & Enablements",
      cards: [
        {
          number: "1",
          titleLine1: "EXECUTIONAL",
          titleLine2: "ASSESSMENT FOUNDATION",
          tagline: "From real-world execution into a scalable assessment practice",
          description: "Builds on CETL's executional learning, advisory and challenge-based formats.",
          includes: [
            { icon: "Target", text: "Captures performance signals under real working conditions" },
            { icon: "Users", text: "Builds on CETL's executional learning, advisory and challenge-based formats" },
            { icon: "ClipboardCheck", text: "Transforms observation into structured capability judgement" },
            { icon: "ShieldCheck", text: "Creates a second strategic pillar without major new infrastructure" },
          ],
          footer: [{ icon: "Landmark", text: "Assessment Pillar" }],
        },
        {
          number: "2",
          ribbon: "CORE PRODUCT",
          featured: true,
          titleLine1: "CAPABILITY AUDIT &",
          titleLine2: "SKILLS DUE DILIGENCE",
          tagline: "Independent, decision-grade capability insight",
          description: "Assessment through real business cases, not staged exercises.",
          includes: [
            { icon: "Briefcase", text: "Assessment through real business cases, not staged exercises" },
            { icon: "FileText", text: "Transparent purpose, criteria and application of results" },
            { icon: "Map", text: "Organization-wide capability view for advance, develop or redeploy decisions" },
            { icon: "Users", text: "Relevant for transformation, succession, PE and sponsor contexts" },
          ],
          footer: [{ icon: "BarChart2", text: "Board-Ready Insight" }],
        },
        {
          number: "3",
          ribbon: "DELIVERY MODEL",
          titleLine1: "PHASED AUDIT",
          titleLine2: "ARCHITECTURE",
          tagline: "A structured journey from baseline to capability roadmap",
          description: "Baseline alignment, scope definition and stakeholder calibration.",
          includes: [
            { icon: "Calendar", text: "Baseline alignment, scope definition and stakeholder calibration" },
            { icon: "Search", text: "Embedded assessment through real delivery observations" },
            { icon: "Map", text: "Evidence-based capability mapping and advisory synthesis" },
            { icon: "Users", text: "Multi-assessor perspective with academic rigor" },
          ],
          footer: [{ icon: "Clock", text: "Structured Delivery Engine" }],
        },
        {
          number: "4",
          ribbon: "DIFFERENTIATOR",
          titleLine1: "THE CETL",
          titleLine2: "EDGE",
          tagline: "Why this model stands out in the market",
          description: "Independent third-party perspective, less exposed to internal politics.",
          includes: [
            { icon: "ShieldCheck", text: "Independent third-party perspective, less exposed to internal politics" },
            { icon: "Scale", text: "Transparent and defensible by design" },
            { icon: "TrendingUp", text: "Predictive because capability is observed in action" },
            { icon: "Euro", text: "One engagement can unlock both audit insight and development momentum" },
          ],
          footer: [{ icon: "Euro", text: "Audit-to-Enablement Model" }],
        },
      ],
    },
  ],

  ECOSYSTEM_NODES: [
    { number: "1", title: "Community & Collaboration", description: "Peer exchange, expert access, interdisciplinary collaboration and community-powered learning." },
    { number: "2", title: "Technology & Methodic Literacy", description: "Practical understanding of Data, AI, automation, governance and technology-related decision-making." },
    { number: "3", title: "Case-based Education", description: "Learning built around real organizations, business challenges, workflows and use cases." },
    { number: "4", title: "Scientific Coordination", description: "Academic rigor, curriculum quality, methodological consistency and university collaboration." },
    { number: "5", title: "Innovation & Idea Labs", description: "Structured ideation, experimentation, use-case development, prototyping and validation." },
    { number: "6", title: "Education as a Service Platform", description: "Modular and scalable capability programmes designed to evolve with organizational demand." },
  ],

  NETWORK_LAYERS: [
    {
      number: "1",
      title: "Corporate Access",
      subtitle: "Tech Execution Community & Corporate Network",
      copy: "Enterprise demand, applied technology experience and project access through the broader Tech Execution Community and corporate ecosystem.",
      logoPlaceholders: ["Raiffeisen Bank International", "Erste Group", "OMV", "A1", "Palfinger", "Specific-Group"],
      outcome: "Direct enterprise relevance and project opportunities.",
    },
    {
      number: "2",
      title: "Community Reach",
      subtitle: "CETL Community & Flagship Platform",
      copy: "European Data, AI and technology formats that create visibility, engagement, challenge-based co-creation and market relevance.",
      logoPlaceholders: ["Europe Tech Hackathon", "City of Vienna", "Vienna Business Agency", "ÖBB", "Siemens", "AIT"],
      outcome: "Visibility, engagement and access to interdisciplinary expertise.",
    },
    {
      number: "3",
      title: "Academic Credibility",
      subtitle: "Founders' Networks & Academic Partners",
      copy: "Academic depth, curriculum quality, research access and collaboration potential through university, institute and founder networks.",
      logoPlaceholders: ["TU Wien", "Institute of Management Accountants", "Lauder Business School"],
      outcome: "Content quality, applied rigor and innovation depth.",
    },
  ],

  ROLE_CARDS: [
    { title: "Everyday AI", audience: "Employees and business users", purpose: "Apply AI effectively, safely and productively in daily work." },
    { title: "Business AI", audience: "Business experts and AI Champions", purpose: "Identify opportunities, shape use cases, support adoption and connect business demand with technical teams." },
    { title: "AI Expert", audience: "Data, technology and internal development professionals", purpose: "Validate, design and implement Data and AI solutions in the organization's technical context." },
    { title: "AI Leadership", audience: "Executives and senior decision-makers", purpose: "Steer strategy, investments, governance, operating models, risk and organizational transformation." },
  ],

  EVIDENCE_STATS: [
    { figure: "70%", claim: "of large-scale transformation projects fail to meet their intended objectives.", source: "McKinsey & Company", interpretation: "The majority of transformation investments do not deliver their planned outcomes — often due to capability gaps, not technology.", isIllustrative: false },
    { figure: "85%", claim: "of AI projects fail to move from pilot to production and create expected business value.", source: "Gartner", interpretation: "Governance, organizational readiness and execution structures — not models — are the limiting factors.", isIllustrative: false },
    { figure: "24%", claim: "Illustrative operational execution capability vs. documented AI strategy (82% leadership awareness, 54% documented strategy).", source: "CETL Execution Readiness Index", interpretation: "The gap between documented strategy and real operational execution capability is CETL's central focus area.", isIllustrative: true },
  ],

  PILLARS: [
    { number: "01", icon: "Brain", title: "Executional Learning", subtitle: "From Capability to Execution", description: "A standardized Data & AI foundation combined with customized activation, role-based journeys and guided use-case work.", items: ["8-day standardized Data & AI Foundation", "Role-based specialization tracks", "Use-case assessment and prioritization", "7-day Executional Learning support pool"] },
    { number: "02", icon: "TrendingUp", title: "Embedded Engineering", subtitle: "Capability That Stays", description: "CETL experts work temporarily alongside internal teams to activate selected use cases, validate prototypes, enable workflows and transfer technical methods.", items: ["Forward-Deployed-Engineer-inspired approach", "Use-case activation and prototyping", "Knowledge transfer through joint execution", "Technical enablement close to the work"] },
    { number: "03", icon: "Award", title: "Technical Assessment", subtitle: "Vendor-Neutral. Uncompromised.", description: "Independent architecture reviews, feasibility assessments, data and governance readiness evaluations.", items: ["Vendor-neutral architecture reviews", "Data and governance readiness assessments", "AI operating-model reviews", "Implementation-readiness assessments"] },
  ],

  METHODOLOGY_STEPS: [
    { n: "01", icon: "Brain", title: "Understand", description: "Participants build the technological and methodological literacy required to evaluate Data, AI, automation, opportunities, limitations and risks realistically." },
    { n: "02", icon: "Layers", title: "Apply", description: "Organizational tools, processes, standards and work contexts are integrated directly into the learning journey." },
    { n: "03", icon: "Network", title: "Transfer", description: "Cross-industry examples, academic insight and proven methods create patterns that can be transferred into the organization." },
    { n: "04", icon: "Target", title: "Execute", description: "Every journey ends in a concrete organizational output: a use case, prototype, business case, operating-model decision or implementation roadmap." },
  ],

  PROGRAMS: [
    { tag: "Foundation", title: "Enterprise Data & AI Capability Programme", format: "3–12 months", level: "All roles", description: "One coordinated capability system for the entire organization. Shared foundation, role-based specialization and guided projects.", href: "#programmes" },
    { tag: "Specialization", title: "Everyday AI Learning Journey", format: "Modular", level: "Business Users", description: "Apply AI effectively and safely in daily work. Practical, role-specific and connected to real organizational tools." },
    { tag: "Leadership", title: "AI Leadership Programme", format: "Intensive", level: "C-Suite & Board", description: "Steer AI strategy, investments, governance and operating models with genuine technological judgment." },
    { tag: "Technical", title: "AI Expert Track", format: "Deep-Dive", level: "Technical Staff", description: "Validate, design and implement Data and AI solutions in the organization's real technical context." },
  ],

  TAG_COLORS: { Foundation: "gold", Specialization: "blue", Leadership: "muted", Technical: "gold" },

  PROBLEM_ITEMS: [
    { title: "PoC graveyards instead of enterprise operations", desc: "A use case works in a sandbox, but production data, governance, ownership and implementation responsibilities remain unresolved. The result is activity without scalable value creation." },
    { title: "Capability loss through traditional delivery models", desc: "External expertise may temporarily substitute internal capability. When the engagement ends, the organization often remains dependent on the next external intervention." },
    { title: "Technology sovereignty under platform pressure", desc: "Architecture decisions made under time pressure can create long-term lock-in, migration costs and operational dependency." },
    { title: "Governance and data readiness treated too late", desc: "Models and use cases built on unclear data, ownership and governance structures rarely survive the transition into regular enterprise operations." },
  ],

  PARTNERS: [
    { name: "Specific-Group", sub: "Strategic Delivery Partner", logo: "/logos/specific-group.svg", logoWidth: 120, logoHeight: 32 },
    { name: "TU Wien", sub: "Academic Partner", logo: "/logos/tuwien.svg", logoWidth: 80, logoHeight: 40 },
    { name: "Europe Tech Hackathon", sub: "Community Platform", logo: "/logos/eth.svg", logoWidth: 120, logoHeight: 32 },
  ],

  PARTNER_GROUPS: [
    {
      label: "Academic Partners",
      partners: [
        { name: "TU Wien", sub: "Academic Partner", logo: "/logos/academy/tuwien.webp" },
        { name: "BOKU Vienna", sub: "Academic Partner", logo: "/logos/academy/boku.png" },
        { name: "MedUni Vienna", sub: "Academic Partner", logo: "/logos/academy/meduni.webp" },
        { name: "BFI Vienna", sub: "Academic Partner", logo: "/logos/academy/bfi.png" },
        { name: "Lauder Business School", sub: "Academic Partner", logo: "/logos/academy/lauder.png" },
        { name: "The Institute of Management Accountants", sub: "Academic Partner", logo: "/logos/academy/ima.jpg" },
        { name: "ÖGIG", sub: "Academic Partner", logo: "/logos/academy/oegig.png" },
      ],
    },
    {
      label: "Community Partners",
      partners: [
        { name: "City of Vienna", sub: "Community Partner", logo: "/logos/community/stadtwien.svg" },
        { name: "Vienna Business Agency", sub: "Community Partner", logo: "/logos/community/waa.png" },
        { name: "Europe Direct", sub: "Community Partner", logo: "/logos/community/edic.png" },
        { name: "EIT", sub: "Community Partner", logo: "/logos/community/eit.jpg" },
        { name: "Tech Execution Community", sub: "Community Partner", logo: "/logos/community/tec.png" },
        { name: "Sustainista", sub: "Community Partner", logo: "/logos/community/sustainista.png" },
      ],
    },
    {
      label: "Industry Partners",
      partners: [
        { name: "Siemens", sub: "Industry Partner", logo: "/logos/industry/siemens.webp" },
        { name: "ÖBB", sub: "Industry Partner", logo: "/logos/industry/oebb.webp" },
        { name: "Raiffeisen", sub: "Industry Partner", logo: "/logos/industry/raiffeisen.svg" },
        { name: "Wien Energie", sub: "Industry Partner", logo: "/logos/industry/wienenergie.svg" },
        { name: "Caritas St. Barbara", sub: "Industry Partner", logo: "/logos/industry/caritasstbarbara.png" },
      ],
    },
  ],

  RESEARCH_STATS: [
    { id: "transformation", kind: "ring", value: "70%", label: "Transformation projects miss objectives", detail: "Most fail not due to technology, but to organizational capability and execution gaps.", source: "McKinsey & Company" },
    { id: "ai-value", kind: "gauge", value: "85%", label: "AI projects fail to scale", detail: "Governance, data readiness and execution structures are the real limiting factors.", source: "Gartner" },
    { id: "execution", kind: "bars", value: "24%", label: "Operational execution readiness", detail: "Illustrative CETL benchmark. Not a scientific study.", source: "CETL Execution Readiness Index" },
  ],

  EXECUTION_GAP: {
    label: "Illustrative CETL Execution Readiness Index",
    detail: "Not a scientific study. Illustrative benchmark values.",
    rows: [
      { label: "Leadership AI awareness", value: 82 },
      { label: "Documented AI strategy", value: 54 },
      { label: "Governance and data maturity", value: 37 },
      { label: "Operational execution capability", value: 24 },
    ],
  },

  INST_STATS: [
    { value: "20+", label: "Years of Industry Experience", sub: "Cross-business industry experience" },
    { value: "ELaaS", label: "Executional Learning as a Service", sub: "Connecting renowned academic partnerships, industries & community for execution-driven upskilling" },
    { value: "Own Community", label: "Flagship Community Format", sub: "\"Central Europe Tech Hackathon\" with the City of Vienna and numerous partners" },
    { value: "50+", label: "Trainers & Lecturers", sub: "Cross-industry pool of trainers and lecturers" },
    { value: "12+", label: "Academic Projects", sub: "Completed academic projects" },
  ],

  TESTIMONIALS: [
    { quote: "AI initiatives do not fail because of the technology. They fail because of the organization. CETL helped us understand that before we released the next round of budget.", role: "Head of Digital Transformation", sector: "Austrian banking", orgSize: "Large enterprise" },
    { quote: "We had an AI strategy. What we did not have was the internal capability to execute it. The Embedded Engineering programme changed that structurally rather than superficially.", role: "Chief Data Officer", sector: "Austrian industry", orgSize: "Upper mid-market" },
    { quote: "The Architecture Review identified vendor-lock-in structures that we had not recognized internally. Vendor-neutral, methodical and independent — exactly what is required before a major platform decision.", role: "Head of IT Strategy", sector: "Public sector", orgSize: "Public institution" },
  ],

  COMMUNITY: {
    pills: ["Europe Tech Hackathon", "Executive Roundtables", "Data & AI Exchange", "Meet-ups", "Tech Workshops", "Expert Impulses", "Innovation Labs", "Academic Collaboration"],
    features: [
      { title: "Challenge-Based Co-Creation", desc: "Bring a real Data, AI or technical challenge into the CETL community and access interdisciplinary expertise." },
      { title: "Europe Tech Hackathon", desc: "CETL's flagship community platform — connecting organizations with academic experts, developers and innovation ecosystems." },
      { title: "Executive Knowledge Exchange", desc: "Cross-sector roundtables and expert impulse formats for senior decision-makers." },
    ],
    quote: "Insight and networking converted into measurable delivery outcomes.",
    quoteAttribution: "CETL Community Model",
  },

  FACULTY_POSITIONS: [
    { initials: "MD", role: "Managing Director", desc: "Overall direction, strategy, commercial development and institutional partnerships." },
    { initials: "AD", role: "Academic Director", desc: "Academic quality, curriculum architecture, scientific coordination and university collaboration." },
    { initials: "FD", role: "Faculty Director", desc: "Faculty curation, trainer quality and programme delivery standards." },
    { initials: "ID", role: "Industry Director", desc: "Enterprise relevance, corporate access and cross-sector transfer." },
  ],

  CASE_STUDY: {
    clientTag: "Enterprise Programme",
    client: "RLB OÖ × CETL Institute",
    title: "Executional Learning in Practice",
    desc: "A customized Enterprise Data & AI Capability Programme combining a shared foundation, differentiated role tracks and guided project work. Structured as an integrated organizational enablement system rather than a conventional training catalogue.",
    metrics: [
      { label: "Foundation Programme", value: "15 days", highlight: true },
      { label: "Role Tracks", value: "2 × 8 days" },
      { label: "Total Programme Scope", value: "31 days", highlight: true },
      { label: "Guided Projects", value: "Own use case" },
      { label: "Delivery Model", value: "ELaaS" },
    ],
    principles: [
      { num: "01", title: "Role-Specific Enablement", desc: "Learning journeys for AI Leadership, Everyday AI, AI Champions and internal AI experts, aligned with responsibility and maturity." },
      { num: "02", title: "Guided Projects with Output", desc: "Each learning path concludes with structured use cases, business cases or implementation contributions, from initial canvas to final pitch." },
      { num: "03", title: "Direct Contribution to Strategy", desc: "Programme outputs feed into the organization's use-case pipeline, prioritization logic and transformation agenda." },
    ],
  },

  INTERSECTION_CATEGORIES: [
    { label: "Academic & Professional", partners: [{ name: "TU Wien", desc: "Technical University of Vienna" }, { name: "Institute of Management Accountants", desc: "Professional institution" }, { name: "Lauder Business School", desc: "Business school" }] },
    { label: "Community & Public Ecosystem", partners: [{ name: "City of Vienna", desc: "Municipal partner" }, { name: "Vienna Business Agency", desc: "Innovation ecosystem" }, { name: "ÖBB", desc: "Rail infrastructure" }, { name: "AIT", desc: "Austrian Institute of Technology" }, { name: "Europe Tech Hackathon", desc: "Flagship community platform" }] },
    { label: "Corporate Access Network", partners: [{ name: "Raiffeisen Bank International", desc: "Banking" }, { name: "Erste Group", desc: "Financial services" }, { name: "OMV", desc: "Energy" }, { name: "Palfinger", desc: "Industrial" }, { name: "Specific-Group", desc: "Technology delivery" }] },
  ],

  QUOTES: [],

  FAQ_ITEMS: [
    { q: "What distinguishes CETL from a traditional training provider?", a: "CETL does not treat learning as an isolated activity. Programmes are designed around organizational priorities, participant roles, real use cases and implementation pathways. Capability building is combined with mentoring, guided projects, technical enablement and, where required, embedded execution support." },
    { q: "What distinguishes CETL from a consulting company?", a: "CETL focuses on building internal organizational capability. While engagements may include assessments, programme design, technical enablement or embedded specialists, the objective is knowledge transfer and stronger internal execution capacity rather than permanent external dependency." },
    { q: "What is Executional Learning as a Service (ELaaS)?", a: "ELaaS is CETL's modular model for combining foundational capability building, role-based specialization, use-case activation, mentoring, technical enablement and ecosystem access in one coordinated engagement." },
    { q: "Can CETL customize programmes?", a: "Yes. CETL combines standardized methodological foundations with organization-specific customization based on strategy, roles, processes, maturity, technology context and business priorities." },
    { q: "Who participates in CETL programmes?", a: "Programmes may be designed for executives, business users, AI Champions, data and technology experts, transformation teams and cross-functional organizational groups." },
    { q: "Does CETL support implementation?", a: "Depending on the package, CETL can provide use-case activation, prototype validation, workflow enablement, technical mentoring and temporary embedded engineering support." },
    { q: "How long does an engagement take?", a: "Focused interventions may be delivered as individual modules. Broader ELaaS programmes typically run for several months depending on the number of roles, programme components, guided projects and embedded support requirements." },
    { q: "Is CETL vendor-neutral?", a: "CETL's capability-building and assessment activities are designed around organizational requirements rather than software resale. Technology recommendations are based on suitability, integration context, governance requirements and long-term organizational value." },
    { q: "Does CETL work with insurance organizations?", a: "No. CETL activities are directed exclusively at organizations outside the insurance sector. Insurance-specific compliance, regulatory topics and business mandates are explicitly excluded." },
    { q: "How does an engagement begin?", a: "An engagement begins with a strategic discovery conversation. CETL assesses the organizational context, target groups, capability priorities, use cases and required activation level before recommending an appropriate programme or package." },
  ],

  CONTACT_ITEMS: [
    { label: "Institute", value: "CETL Institute", href: null },
    { label: "Location", value: "Vienna, Austria", href: null },
    { label: "Email", value: "office@cetl-institute.eu", href: "mailto:office@cetl-institute.eu" },
  ],

  CONTACT_INTEREST_OPTIONS: [
    "Executional Learning Foundation", "Executional Learning Customized", "Flagship Embedded Engineering",
    "Executional Community Package", "Enterprise Data & AI Programme", "Customized Education",
    "Technical Assessment", "Academic Partnership", "Strategic Partnership", "Other",
  ],

  INSIGHTS: ARTICLE_META.en,

  UI: {
    nav: { ctaContact: "Discuss Your Capability Agenda", toggleMenu: "Toggle navigation menu" },

    hero: {
      eyebrow: "Central European Tech Leadership Institute",
      headlineLine1: "Executional Learning",
      headlineAccent: "as a Service",
      subheadline: "From capability building to execution and scalable impact.",
      body: "CETL Institute is the unique bridge between academic excellence, industry practice, and community.",
      bodyParagraphs: [
        "CETL Institute is the unique bridge between academic excellence, industry practice, and community!",
        "Through our proprietary ELaaS (Executional Learning as a Service), we accompany organizations and their talent across industries along real execution — tailored to roles, processes, and strategic as well as operational objectives.",
        "Instead of classical course blocks (standard trainings, upskilling programs, or consulting-led workshops), we help organizations navigate the current wave of transformation with ELaaS: accelerating AI transformation pressure, advancing automation across entire industries, and the relentless demand for process and efficiency gains.",
      ],
      ctaPrimary: "Explore the ELaaS Model",
      ctaSecondary: "Discuss Your Capability Agenda",
      supportingLine: "Academic excellence × Industry practice × Community-powered execution",
      microProof: ["Customized to organizational priorities", "Role-based capability journeys", "Real use cases and implementation pathways", "Knowledge transfer that stays"],
      headlineGradient: "as a Service",
      headlineLine3: "",
      paragraph: "",
      stats: [],
      ticker: [],
      badgeLocation: "Vienna, Austria",
      badgeVienna: "Vienna, Austria",
      badgeTUWien: "TU Wien",
      badgeFDE: "ELaaS",
      photoCaption: "",
    },

    problem: {
      eyebrow: "The Organizational Execution Gap",
      headline: "The gap is not awareness.\nIt is operationalization.",
      intro: "Large-scale Data and AI initiatives rarely fail because organizations lack ambition. They fail because strategy, capability, data readiness, governance and technical execution are treated as separate activities.",
      closingStatement: "The answer is not another isolated training programme or standalone pilot. The answer is a coordinated capability and execution system.",
      cta: "Explore Executional Learning",
      quoteBefore: "The gap is not",
      quoteHighlight1: "awareness",
      quoteMiddle: " — it is",
      quoteHighlight2: "operationalization",
      answer: "The answer is a coordinated capability and execution system.",
    },

    elaas: {
      eyebrow: "The CETL Operating Model",
      headline: "A standardized core. Customized activation. Execution close to the work.",
      body: "Executional Learning as a Service combines structured Data & AI foundations with organization-specific activation, role-based learning journeys, guided use cases, embedded enablement and ecosystem access. ELaaS does not separate learning from organizational execution.",
      callout: "Executional Learning days are a flexible support pool — not additional classroom days. They may include:",
      calloutItems: ["Mentoring and one-to-one enablement", "Use-case assessment and ideation", "Prioritization and strategic-fit analysis", "Cross-business alignment sessions", "Expert sessions and online enablement", "Panels and community impulses", "Project support"],
      cta: "Explore the Complete ELaaS Model",
    },

    productPortfolio: {
      eyebrow: "The CETL Product Portfolio",
      headline: "A system of learning, assessment and enablement.",
      intro: "Our product portfolio connects structured executional learning with independent capability assessment and hands-on enablement — modular and combinable, from foundation to embedded execution.",
    },

    portfolio: {
      eyebrow: "CETL Institute | Product Portfolio",
      headline: "Four integrated capabilities.\nOne path from learning to impact.",
      intro: "CETL combines education, organizational activation, embedded technical enablement and community-powered co-creation in one coordinated portfolio. Each capability may be commissioned individually or integrated into a broader ELaaS engagement.",
    },

    packages: {
      eyebrow: "CETL Institute | Package Portfolio",
      headline: "Choose the right level of activation.",
      intro: "CETL offers structured engagement levels ranging from customized Data & AI capability building to embedded execution and community-powered co-creation.",
      callout: "Executional Learning days are a support pool, not additional course days.",
    },

    outcomes: {
      label: "Why This Matters",
      items: [
        { title: "Capability Building", copy: "Build internal AI and data literacy that lasts." },
        { title: "Execution Readiness", copy: "Move from use-case ideas to prioritized action." },
        { title: "Scalable Impact", copy: "Create reusable, organization-wide momentum." },
      ],
    },

    differentiators: {
      headline: "Why organizations choose CETL",
      items: [
        { title: "Executional by Design", copy: "From learning to measurable action." },
        { title: "Academic Excellence", copy: "Leading universities, professional institutions and applied rigor." },
        { title: "Role- and Industry-Customized", copy: "Tailored to business context, maturity and organizational responsibility." },
        { title: "Capability That Stays", copy: "Internal talent and organizational knowledge, not dependency." },
        { title: "Community & Ecosystem Power", copy: "Access to broad Data, AI, technology and academic networks." },
      ],
    },

    methodology: {
      label: "The CETL Method",
      title: "Learn, apply and execute.",
      subtitle: "Executional Learning does not isolate education from the organization's real work. Knowledge is connected directly to processes, standards, priorities and use cases.",
      cta: "Explore the Method",
      closingLine: "Every learning journey must create greater internal capability and a concrete next step.",
    },

    ecosystem: {
      eyebrow: "The CETL Ecosystem",
      headline: "CETL Institute Ecosystem",
      headlineSuffix: "& Services",
      intro: "Large-scale Data and AI initiatives rarely fail because organizations lack ambition. They fail because strategy, capability, data readiness, governance and technical execution are treated as separate activities. Our unique CETL ecosystem connects six building blocks into one coordinated system of knowledge, application and execution that directly serves as the fundament of the unique Executional Learning we deliver.",
      fundamentLabel: "Our Fundament — CETL Ecosystem",
      servicesLabel: "Our Services for Executional Learning",
      bottomBand: ["Community-driven learning", "Execution-oriented capability building", "Academic rigor meets real-world deployment"],
    },

    enterprise: {
      eyebrow: "Flagship Enterprise Programme",
      headline: "One programme. Every role. Full operational impact.",
      body: "The Enterprise Data & AI Capability Programme connects a shared organizational foundation with differentiated role-based learning journeys, guided projects and real use cases.",
      facts: ["Modular structure", "Typical duration: 3–12 months", "From employees to executive leadership", "Shared foundation + role-based specialization", "Guided projects and mentoring", "Real organizational outputs"],
      outputs: ["Structured use-case portfolio", "Business case", "Prototype", "Governance recommendation", "Operating-model contribution", "Implementation roadmap"],
      ctaPrimary: "Design an Enterprise Programme",
      ctaSecondary: "Request the Role Framework",
    },

    embedded: {
      eyebrow: "From Enablement to Execution",
      headline: "Work alongside your teams. Build capability while delivering.",
      body: "Embedded Engineering extends the CETL model from capability building into hands-on technical activation. CETL experts work temporarily alongside internal teams to activate selected use cases, validate prototypes, enable workflows and transfer technical methods. The objective is stronger internal execution capability, not permanent external dependency.",
      modules: ["Use-Case Activation", "Prototyping & Validation", "Workflows & Automation", "No-Code / Low-Code Enablement", "Technical Enablement", "Knowledge Transfer", "Data & AI Solution Pathways", "Implementation Readiness", "Governance Integration", "Internal Activation"],
      fde: "CETL applies a Forward-Deployed-Engineer-inspired model in which experts work close to business and technical teams, inside the real organizational context, for a defined period.",
      outcome: "Capability is transferred through joint execution.",
      cta: "Discuss an Embedded Engagement",
      assessmentEyebrow: "Independent Technical Assessment",
      assessmentHeadline: "Technical rigor before major implementation decisions.",
      assessmentBody: "Technical Assessment is a cross-cutting CETL capability supporting execution readiness, architecture quality and informed technology decisions.",
      assessmentItems: ["Vendor-neutral architecture reviews", "Feasibility assessments", "Data and governance readiness assessments", "AI and data operating-model reviews", "Legacy-decommissioning roadmaps", "Risk and dependency analysis", "Implementation-readiness reviews", "Technology-suitability assessments"],
    },

    community: {
      eyebrow: "Community-Powered Execution",
      headline: "Turn exchange and networking into co-creation and delivery opportunities.",
      body: "CETL's community model connects organizations with academic experts, industry practitioners, technology specialists, developers and innovation ecosystems. The Europe Tech Hackathon serves as CETL's flagship community platform, supported by meet-ups, workshops, executive formats and knowledge-exchange activities.",
      formats: ["Europe Tech Hackathon", "Executive roundtables", "Data & AI exchange formats", "Meet-ups and tech workshops", "Expert impulses", "Challenge-based co-creation", "Innovation and idea labs", "Academic collaboration"],
      orgValue: ["Frame a real Data, AI or technical challenge", "Access interdisciplinary expertise", "Validate assumptions", "Develop proof-of-concept pathways", "Create early execution momentum"],
      featuredStatement: "Insight + networking converted into measurable delivery outcomes.",
      ctaPrimary: "Bring a Challenge to the Community",
      ctaSecondary: "Explore the Europe Tech Hackathon",
      label: "Community",
      title: "Community-Powered Execution",
      subtitle: "Turn exchange into co-creation.",
      advisorCta: "Discuss Your Capability Agenda",
      pills: ["Europe Tech Hackathon", "Executive Roundtables", "Data & AI Exchange", "Meet-ups", "Tech Workshops", "Expert Impulses", "Innovation Labs", "Academic Collaboration"],
      features: [
        { title: "Challenge-Based Co-Creation", desc: "Bring a real challenge into the CETL community." },
        { title: "Europe Tech Hackathon", desc: "CETL's flagship community platform." },
        { title: "Executive Knowledge Exchange", desc: "Cross-sector roundtables and expert formats." },
      ],
      quote: "Insight and networking converted into measurable delivery outcomes.",
      quoteAttribution: "CETL Community Model",
    },

    network: {
      eyebrow: "The CETL Network Advantage",
      headline: "Three network layers strengthen access, credibility and execution.",
    },

    caseStudy: {
      eyebrow: "Executional Learning in Practice",
      headline: "Proof that capability building can connect directly to organizational execution.",
      body: "A customized Enterprise Data & AI Capability Programme combines a shared foundation, differentiated role tracks and guided project work.",
      cta: "Discuss a Similar Programme",
      label: "Client Case",
      title: "Executional Learning in Practice",
      subtitle: "RLB OÖ × CETL Institute",
    },

    evidence: {
      eyebrow: "Studies & Evidence",
      headline: "The execution gap is measurable.",
      body: "Research consistently indicates that technology alone is rarely the limiting factor in large-scale transformation. Organizational capability, data readiness, governance, adoption and execution structures determine whether investments create sustainable value.",
      eriTitle: "CETL Execution Readiness Index",
      eriDesc: "A structured CETL framework for evaluating organizational capability, documented strategy, governance and data maturity, and operational execution readiness.",
      eriNote: "Illustrative CETL benchmark. Not a scientific study.",
      cta: "Explore Research & Frameworks",
    },

    insights: {
      label: "Thought Leadership",
      title: "From research to execution.",
      subtitle: "Frameworks and perspectives for leaders responsible for Data, AI, technology and organizational capability.",
      cta: "View All Insights",
      readCta: "Read the Analysis",
      pageTitle: "Insights",
      pageSubtitle: "Frameworks and perspectives for leaders.",
      back: "Back to Insights",
      published: "Published",
      byline: "CETL Institute",
      ctaTitle: "Discuss Your Capability Agenda",
      ctaText: "Connect with CETL to explore how ELaaS can build lasting capability in your organization.",
      ctaButton: "Discuss Your Capability Agenda",
      moreLabel: "More Insights",
      authorLabel: "CETL Institute",
      share: "Share",
      shareCopied: "Copied",
      prevLabel: "Previous",
      nextLabel: "Next",
    },

    testimonials: {
      label: "Voices from Practice",
      title: "What decision-makers say about the difference between awareness and execution.",
      subtitle: "Approved anonymized statements from programme participants.",
      anonymousNote: "Anonymized. Role and sector verified.",
    },

    about: {
      eyebrow: "About CETL Institute",
      headline: "Bridging the gap:\nacademic excellence meets industry execution.",
      body: "CETL Institute operates at the high-value intersection of academic excellence and industrial execution. The institute combines customized education, role-based capability building, embedded technical enablement, scientific coordination and community-powered co-creation.",
      mission: "Build lasting organizational capability at the intersection of technology, leadership and execution.",
      vision: "A Central European ecosystem in which organizations develop the internal competence required to shape technology independently, responsibly and effectively.",
      differentiator: "CETL focuses on competence transfer rather than resource augmentation. The objective is not to substitute the organization. The objective is to strengthen the organization's own ability to decide, prioritize and execute.",
      values: [
        { title: "Academic Rigor", copy: "Scientific coordination, curriculum quality and university collaboration." },
        { title: "Industry Relevance", copy: "Business contexts, real processes, use cases and technical realities." },
        { title: "Execution Orientation", copy: "Guided application, embedded enablement and concrete implementation pathways." },
      ],
    },

    leadership: {
      eyebrow: "Leadership",
      label: "Leadership",
      title: "Institutional direction supported by a curated expert ecosystem.",
      subtitle: "Expertise at the intersection of AI strategy, data governance and enterprise execution.",
      linkedin: "LinkedIn Profile",
      focus: "Focus Areas",
      photoTag: "Managing Director",
      photoAlt: "Alin Kalam, Managing Director, CETL Institute",
    },

    partner: {
      eyebrow: "Strategic Delivery Ecosystem",
      headline: "Enterprise technology experience connected to capability building.",
      body: "Through its strategic ecosystem, CETL connects capability development with broader enterprise technology and transformation experience. Specific-Group contributes an established technology network, delivery experience and access to enterprise project environments across banking, industry and the public sector.",
      cta: "Explore the Partner Ecosystem",
    },

    faq: { label: "Frequently Asked Questions", title: "Questions decision-makers ask first." },

    contact: {
      eyebrow: "Start a Strategic Conversation",
      label: "Contact",
      title: "Build the capability to move from AI ambition to execution.",
      subtitle: "Discuss Your Capability Agenda",
      body: "Whether you are designing an enterprise capability programme, activating a portfolio of use cases, assessing technical readiness or bringing a challenge into CETL's community ecosystem, the first conversation is used to define the organizational context and the right level of activation.",
      targetAudienceLabel: "We work with",
      targetAudienceText: "CEOs, CIOs, CTOs, CDOs, Heads of AI/Data/Digital Transformation, Corporate Academy leaders, HR and People Development leaders, and transformation programme owners.",
      complianceLabel: "Compliance",
      nameLabel: "Full Name",
      namePlaceholder: "Your full name",
      companyLabel: "Organization",
      companyPlaceholder: "Your organization",
      emailLabel: "Business Email",
      emailPlaceholder: "you@organization.com",
      roleLabel: "Your Role",
      rolePlaceholder: "e.g. Chief Data Officer",
      interestLabel: "Area of Interest",
      interestPlaceholder: "Select an area",
      contextLabel: "Organizational Context",
      contextPlaceholder: "Briefly describe your organizational priorities, target groups, current capability level or execution challenges.",
      submit: "Initiate the Conversation",
      successTitle: "Message received.",
      successText: "We will review your context and respond within one business day to discuss the right approach for your organization.",
      mailSubjectPrefix: "CETL Inquiry",
      mailGeneral: "General Inquiry",
      mailFieldName: "Name",
      mailFieldCompany: "Organization",
      mailFieldEmail: "Email",
      mailFieldInterest: "Area of Interest",
      privacyNote: "Your contact details are used only to respond to this inquiry. We do not share your data with third parties.",
    },

    footer: {
      tagline: "CETL Institute is a Central European capability-building and execution ecosystem combining academic excellence, industry practice and community-powered execution.",
      navLabel: "Navigation",
      contactLabel: "Contact",
      location: "Vienna, Austria",
      region: "Central Europe",
      copyright: `© ${new Date().getFullYear()} CETL Institute. All rights reserved.`,
      complianceLine: "All CETL services are directed exclusively at organizations outside the insurance sector.",
    },

    pillars: { label: "What We Do", title: "Three integrated capabilities", subtitle: "From learning to execution" },
    programs: { label: "Programmes", title: "Structured for every role", subtitle: "One foundation. Differentiated journeys.", cta: "Explore Programmes", filterAll: "All", filterLabel: "Filter by level", ctaAdvisor: "Discuss Your Capability Agenda", detailCta: "Learn More" },
    partners: { trusted: "Selected organizations in the CETL ecosystem", blurbBefore: "", blurbHackathon: "Europe Tech Hackathon", blurbAfter: "" },
    research: { label: "Evidence", title: "The execution gap is measurable.", subtitle: "Research consistently supports the case for coordinated capability systems.", cta: "Explore Research" },
    instStats: { label: "The CETL Model at a Glance" },
    intersection: { label: "The CETL Network", title: "Academic excellence × Industry practice × Community execution", subtitle: "Three network layers create access, credibility and execution momentum." },
    faculty: { label: "Institute", positionOpen: "Position to be filled", featuredTitle: "Expert Ecosystem", featuredDesc: "Selected academic, industry and technology experts engaged according to programme requirements." },
    forOrgs: {
      label: "For Organizations",
      title: "Build capability that stays",
      subtitle: "Internal AI and data competence — not external dependency.",
      ctaPrimary: "Discuss Your Capability Agenda",
      ctaSecondary: "Explore the ELaaS Model",
      items: [
        { title: "Executional by Design", desc: "From learning to measurable action." },
        { title: "Academic Excellence", desc: "University partners and applied rigor." },
        { title: "Customized", desc: "Tailored to your roles, processes and strategy." },
        { title: "Capability That Stays", desc: "Knowledge transfer, not dependency." },
      ],
    },
  },
};
